config/routes.rb
KwGis::Application.routes.draw do |map|
  resources :hostings

  resources :tickets
  resources :reports
  resources :user_sessions
  resources :users
  resources(:managers){
    resources :tickets
    resources :hostings
  }
  resources(:home){
    collection do
      get 'print'
    end
  }
  resources :access
  resources :surveys
  resources :gallerys
  
  root :to => "access#index"
  
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
end

app/models/hosting.rb
class Hosting < ActiveRecord::Base
  belongs_to :manager
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_many :tickets
  has_many :hostings
  has_many :surveys
  
  
  def self.find_by_access_code(access)  
    Manager.first(:conditions => ['access = ?', access])
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :manager
  
  validates_presence_of :agendamento_do_evento
  validates_presence_of :informacoes_sobre_o_evento
  validates_presence_of :hotsite
  validates_presence_of :sistema_de_acesso_de_dados_pessoais_no_hotsite
  validates_presence_of :transporte
  validates_presence_of :suporte_telefonico
  validates_presence_of :acompanhamento_telefonico
  validates_presence_of :reserva_de_quarto
  validates_presence_of :dissertativa1
  
  validates_presence_of :jantar
  validates_presence_of :bebidas
  validates_presence_of :musica
  validates_presence_of :dj
  
  validates_presence_of :cafe_da_manha
  validates_presence_of :almoco
  
  validates_presence_of :necessaire
  validates_presence_of :caneca
  validates_presence_of :copo_volt
  validates_presence_of :camiseta
  validates_presence_of :fotografia_com_moldura
  
  validates_presence_of :apresentacao_carol
  validates_presence_of :treinamento_neogrid
  validates_presence_of :entrega_de_trofeus
  validates_presence_of :identidade_visual_do_evento
  validates_presence_of :trofeu
  validates_presence_of :banners_de_auditorio
  
  validates_presence_of :lista_de_contatos_no_verso
  validates_presence_of :numero_de_quarto_no_verso
  validates_presence_of :cores_de_identificacao_de_regiao
  
  validates_presence_of :dissertativa2
  validates_presence_of :dissertativa3
  validates_presence_of :dissertativa4
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :manager
  
  #PAPERCLIP
  has_attached_file :passagem
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout "access"
  def new
    @manager = Manager.find_by_access_code(params[:access_code])
    if @manager
      #GRAVA SESSION
      session[:access_code] = @manager.access    
      #GRAVA NUMERO DE ACESSOS
      @manager.number_of_access = @manager.number_of_access + 1
      @manager.save
      
      if !@manager.survey
        redirect_to surveys_path
      else
        redirect_to gallerys_path
      end
      
    else
      session[:access_code] = nil
      flash[:msg] = "Código de acesso inválido! Caso não tenha recebido seu código, entre em contato com nosso suporte <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a>"
      redirect_to access_path
    end
  end
  
  def create
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_access_code
  def index
    if !@manager.survey
      redirect_to surveys_path
    else
      redirect_to gallerys_path
    end
    #@quarto = Hosting.first(:conditions => ['manager_id = ', @manager])
  end
  
  def print
    @manager.print = @manager.print + 1
    if @manager.save
      redirect_to @manager.tickets.first.passagem.url
    else
      flash[:msg] = "Ocorreu um erro na exibição de sua passagem,por favor, entre em contato com nosso suporte <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a>"
      redirect_to access_path
    end
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_filter :simple_auth
  layout "admin"
  def index
    @managers = Manager.all
  end

  def show
    @manager = Manager.find(params[:id])
  end

  def new
    @manager = Manager.new
  end

  def create
    @manager = Manager.new(params[:manager])
    if @manager.save
      redirect_to @manager, :notice => "Successfully created manager."
    else
      render :action => 'new'
    end
  end

  def edit
    @manager = Manager.find(params[:id])
  end

  def update
    @manager = Manager.find(params[:id])
    if @manager.update_attributes(params[:manager])
      redirect_to @manager, :notice  => "Successfully updated manager."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy
    redirect_to managers_path, :notice => "Successfully destroyed manager."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :simple_auth
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to managers_path, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to managers_path, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/gallerys_helper.rb
module GallerysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hostings_helper.rb
module HostingsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/managers/_form.html.erb
<%= form_for @manager do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </p>
  <p>
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </p>
  <p>
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </p>
  <p>
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </p>
  <p>
    <%= f.label :cellphone %><br />
    <%= f.text_field :cellphone %>
  </p>
  <p>
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </p>
  <p>
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :complement %><br />
    <%= f.text_field :complement %>
  </p>
  <p>
    <%= f.label :neibourhood %><br />
    <%= f.text_field :neibourhood %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :ae %><br />
    <%= f.text_field :ae %>
  </p>
	<p>
    <%= f.label :obs %><br />
    <%= f.text_area :obs %>
  </p>
	<p>
  <%= f.label :warning %><br />
  <%= f.text_area :warning %>
</p>
  <p><%= f.submit %></p>
<% end %>

app/views/managers/edit.html.erb
<% title "Edit Manager" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @manager %> |
  <%= link_to "View All", managers_path %>
</p>

app/views/managers/index.html.erb
<% title "Managers" %>

<table>
  <tr>
    <th>Nome</th>
    <th>Apelido</th>
    <th>E-mail</th>
    <th>Tel 1</th>
    <th>Tel 2.</th>
    <th>Celular</th>
    <th>Cidade</th>
    <th>Estado</th>
    <th>AE</th>
	<th>Cod.</th>
	<th colspan="4">Ações</th>
  </tr>
  <% for manager in @managers %>
    <tr>
      <td><%= manager.name %></td>
      <td><%= manager.nickname %></td>
      <td><%= manager.email %></td>
      <td><%= manager.phone1 %></td>
      <td><%= manager.phone2 %></td>
      <td><%= manager.cellphone %></td>
      <td><%= manager.city %></td>
      <td><%= manager.state %></td>
      <td><%= manager.ae %></td>
	  <td><%= manager.access %></td>
	  <td><%= link_to "Passagem", manager_tickets_path(manager) %></td>
	  <td><%= link_to "Hospedagem", manager_hostings_path(manager) %></td>
      <td><%= link_to "Ver", manager %></td>
      <td><%= link_to "Editar", edit_manager_path(manager) %></td>
      <td><%= link_to "Deletar", manager, :confirm => 'Tem certeza?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "+ Adicionar", new_manager_path %></p>

app/views/managers/new.html.erb
<% title "New Manager" %>

<%= render 'form' %>

<p><%= link_to "Back to List", managers_path %></p>

app/views/managers/show.html.erb
<% title "Manager" %>

<p>
  <strong>Name:</strong>
  <%= @manager.name %>
</p>
<p>
  <strong>Nickname:</strong>
  <%= @manager.nickname %>
</p>
<p>
  <strong>Email:</strong>
  <%= @manager.email %>
</p>
<p>
  <strong>Rg:</strong>
  <%= @manager.rg %>
</p>
<p>
  <strong>Cpf:</strong>
  <%= @manager.cpf %>
</p>
<p>
  <strong>Phone1:</strong>
  <%= @manager.phone1 %>
</p>
<p>
  <strong>Phone2:</strong>
  <%= @manager.phone2 %>
</p>
<p>
  <strong>Cellphone:</strong>
  <%= @manager.cellphone %>
</p>
<p>
  <strong>Street:</strong>
  <%= @manager.street %>
</p>
<p>
  <strong>Number:</strong>
  <%= @manager.number %>
</p>
<p>
  <strong>Complement:</strong>
  <%= @manager.complement %>
</p>
<p>
  <strong>Neibourhood:</strong>
  <%= @manager.neibourhood %>
</p>
<p>
  <strong>City:</strong>
  <%= @manager.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @manager.state %>
</p>
<p>
  <strong>Ae:</strong>
  <%= @manager.ae %>
</p>
<p>
  <strong>Access:</strong>
  <%= @manager.access %>
</p>
<p>
  <strong>Obs:</strong>
  <%= @manager.obs %>
</p>
<p>
  <strong>Aviso:</strong>
  <%= @manager.warning %>
</p>

<p>
  <%= link_to "Edit", edit_manager_path(@manager) %> |
  <%= link_to "Destroy", @manager, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", managers_path %>
</p>