config/routes.rb
KwGis::Application.routes.draw do |map|
  resources :hostings

  resources :tickets
  resources :reports
  resources :user_sessions
  resources :users
  resources(:managers){
    resources :tickets
    resources :hostings
  }
  resources(:home){
    collection do
      get 'print'
    end
  }
  resources :access
  resources :surveys
  resources :gallerys
  
  root :to => "access#index"
  
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
end

app/models/hosting.rb
class Hosting < ActiveRecord::Base
  belongs_to :manager
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_many :tickets
  has_many :hostings
  has_many :surveys
  
  
  def self.find_by_access_code(access)  
    Manager.first(:conditions => ['access = ?', access])
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :manager
  
  validates_presence_of :agendamento_do_evento
  validates_presence_of :informacoes_sobre_o_evento
  validates_presence_of :hotsite
  validates_presence_of :sistema_de_acesso_de_dados_pessoais_no_hotsite
  validates_presence_of :transporte
  validates_presence_of :suporte_telefonico
  validates_presence_of :acompanhamento_telefonico
  validates_presence_of :reserva_de_quarto
  validates_presence_of :dissertativa1
  
  validates_presence_of :jantar
  validates_presence_of :bebidas
  validates_presence_of :musica
  validates_presence_of :dj
  
  validates_presence_of :cafe_da_manha
  validates_presence_of :almoco
  
  validates_presence_of :necessaire
  validates_presence_of :caneca
  validates_presence_of :copo_volt
  validates_presence_of :camiseta
  validates_presence_of :fotografia_com_moldura
  
  validates_presence_of :apresentacao_carol
  validates_presence_of :treinamento_neogrid
  validates_presence_of :entrega_de_trofeus
  validates_presence_of :identidade_visual_do_evento
  validates_presence_of :trofeu
  validates_presence_of :banners_de_auditorio
  
  validates_presence_of :lista_de_contatos_no_verso
  validates_presence_of :numero_de_quarto_no_verso
  validates_presence_of :cores_de_identificacao_de_regiao
  
  validates_presence_of :dissertativa2
  validates_presence_of :dissertativa3
  validates_presence_of :dissertativa4
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :manager
  
  #PAPERCLIP
  has_attached_file :passagem
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout "access"
  def new
    @manager = Manager.find_by_access_code(params[:access_code])
    if @manager
      #GRAVA SESSION
      session[:access_code] = @manager.access    
      #GRAVA NUMERO DE ACESSOS
      @manager.number_of_access = @manager.number_of_access + 1
      @manager.save
      
      if !@manager.survey
        redirect_to surveys_path
      else
        redirect_to gallerys_path
      end
      
    else
      session[:access_code] = nil
      flash[:msg] = "Código de acesso inválido! Caso não tenha recebido seu código, entre em contato com nosso suporte <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a>"
      redirect_to access_path
    end
  end
  
  def create
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_access_code
  def index
    if !@manager.survey
      redirect_to surveys_path
    else
      redirect_to gallerys_path
    end
    #@quarto = Hosting.first(:conditions => ['manager_id = ', @manager])
  end
  
  def print
    @manager.print = @manager.print + 1
    if @manager.save
      redirect_to @manager.tickets.first.passagem.url
    else
      flash[:msg] = "Ocorreu um erro na exibição de sua passagem,por favor, entre em contato com nosso suporte <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a>"
      redirect_to access_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :simple_auth
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to managers_path, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to managers_path, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/gallerys_helper.rb
module GallerysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hostings_helper.rb
module HostingsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/index.html.erb
<%=form_tag new_acces_path, :method => :get %>
<div id="Tube">
	
	<%if flash[:msg]%>
		<div id="Warning">
			<%=raw(flash[:msg])%>
		</div>
	<%end%>
	<div id="TubeContent">
		<div id="AccessCode">
			<%=text_field_tag :access_code%>
		</div>
		<div id="Access">
			<%=image_submit_tag("bt_access.jpg")%>
		</div>
	</div>
</div>
</form>

app/views/home/index.html.erb
<div id="MainBox">
	<div id="Salute">
		Bem Vindo <%=@manager.nickname%>_
	</div>
	
	<div id="Box" class="Passagem">
		<h1><%=image_tag("tit_passagem.gif")%></h1>
		<%if @manager.tickets.first%>
			<%if !@manager.warning.blank?%>
				<div id="Warning">
					<%=@manager.warning%>
				</div>
			<%end%>
			
			<label><strong>Ida:</strong></label><br />
			 <br />
			<label>Voo:</label><%=@manager.tickets.first.ida_voo%><br />
			 <br />
			<label>DE:</label> <%=@manager.tickets.first.ida_origem%> <%=@manager.tickets.first.ida_data.strftime("%d/%m/%Y")%> / <%=@manager.tickets.first.ida_horario_saida.strftime("%H:%M")%> <br />
			 <br />
			<label>PARA:</label> <%=@manager.tickets.first.ida_destino%> <%=@manager.tickets.first.ida_data.strftime("%d/%m/%Y")%> / <%=@manager.tickets.first.ida_horario_chegada.strftime("%H:%M")%> <br />
			 <br />
			<br />
		
			<label><strong>Volta:</strong></label><br />
			<br />
			<label>Voo:</label><%=@manager.tickets.first.vinda_voo%><br />
			 <br />
			<label>DE:</label> <%=@manager.tickets.first.vinda_origem%> <%=@manager.tickets.first.vinda_data.strftime("%d/%m/%Y")%> / <%=@manager.tickets.first.vinda_horario_saida.strftime("%H:%M")%> <br />
			 <br />
			<label>PARA:</label> <%=@manager.tickets.first.vinda_destino%> <%=@manager.tickets.first.vinda_data.strftime("%d/%m/%Y")%> / <%=@manager.tickets.first.vinda_horario_chegada.strftime("%H:%M")%> <br />
			 <br />
			<label>Cód. de Reserva: </label> <%=@manager.tickets.first.codigo_reserva%> / <label>E-Ticket: </label> <%=@manager.tickets.first.e_ticket%><br />

			 <br />
			<span><%=link_to(image_tag("bt_print.gif"), print_home_index_path, :target => "_blank") if !@manager.tickets.first.passagem.blank?%></span>
	
			
		<%end%>
	</div>
	
	<div id="Box" class="Hospedagem">
		<h1><%=image_tag("tit_hospedagem.gif")%></h1>
		
		<label>hotel:</label> Tauá Hotel & Convention Atibaia <br /> <br />
		<label>Cidade:</label> Atibaia <label>Estado:</label> SP <br /> <br />
		<label>Quarto:</label> <%=@manager.hostings.first.bedroom %> <br /> <br />
		<label>Check-in:</label> 24/08 às 15h00 <br /> <br />
		<label>Check-out:</label> 25/08 às 12h00 <br /> <br />
		<label>Almoço e Jantar:</label> 24 a 25/08 / 13h00 e 20h00 <br /> <br />
		<label>Coffee Break (tarde):</label> 25/08 / 16h00 <br /> <br />
		<label>Informações:</label><br /> http://www.taua.com.br/atibaia/ <br />
		<br />
		<br />
			<i>
				*Em caso de dúvidas, contate nosso suporte através do email: <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a> 
				Ou através do telefone 11 2427.8880 (Bruno)
			</i>
	</div>
	
	<div class="clear"></div>
</div>