config/routes.rb
KwGis::Application.routes.draw do |map|
  resources :hostings

  resources :tickets
  resources :reports
  resources :user_sessions
  resources :users
  resources(:managers){
    resources :tickets
    resources :hostings
  }
  resources(:home){
    collection do
      get 'print'
    end
  }
  resources :access
  resources :surveys
  resources :gallerys
  
  root :to => "access#index"
  
  map.login "login", :controller => "user_sessions", :action => "new"
  map.logout "logout", :controller => "user_sessions", :action => "destroy"
end

app/models/hosting.rb
class Hosting < ActiveRecord::Base
  belongs_to :manager
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_many :tickets
  has_many :hostings
  has_many :surveys
  
  
  def self.find_by_access_code(access)  
    Manager.first(:conditions => ['access = ?', access])
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :manager
  
  validates_presence_of :agendamento_do_evento
  validates_presence_of :informacoes_sobre_o_evento
  validates_presence_of :hotsite
  validates_presence_of :sistema_de_acesso_de_dados_pessoais_no_hotsite
  validates_presence_of :transporte
  validates_presence_of :suporte_telefonico
  validates_presence_of :acompanhamento_telefonico
  validates_presence_of :reserva_de_quarto
  validates_presence_of :dissertativa1
  
  validates_presence_of :jantar
  validates_presence_of :bebidas
  validates_presence_of :musica
  validates_presence_of :dj
  
  validates_presence_of :cafe_da_manha
  validates_presence_of :almoco
  
  validates_presence_of :necessaire
  validates_presence_of :caneca
  validates_presence_of :copo_volt
  validates_presence_of :camiseta
  validates_presence_of :fotografia_com_moldura
  
  validates_presence_of :apresentacao_carol
  validates_presence_of :treinamento_neogrid
  validates_presence_of :entrega_de_trofeus
  validates_presence_of :identidade_visual_do_evento
  validates_presence_of :trofeu
  validates_presence_of :banners_de_auditorio
  
  validates_presence_of :lista_de_contatos_no_verso
  validates_presence_of :numero_de_quarto_no_verso
  validates_presence_of :cores_de_identificacao_de_regiao
  
  validates_presence_of :dissertativa2
  validates_presence_of :dissertativa3
  validates_presence_of :dissertativa4
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :manager
  
  #PAPERCLIP
  has_attached_file :passagem
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout "access"
  def new
    @manager = Manager.find_by_access_code(params[:access_code])
    if @manager
      #GRAVA SESSION
      session[:access_code] = @manager.access    
      #GRAVA NUMERO DE ACESSOS
      @manager.number_of_access = @manager.number_of_access + 1
      @manager.save
      
      if !@manager.survey
        redirect_to surveys_path
      else
        redirect_to gallerys_path
      end
      
    else
      session[:access_code] = nil
      flash[:msg] = "Código de acesso inválido! Caso não tenha recebido seu código, entre em contato com nosso suporte <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a>"
      redirect_to access_path
    end
  end
  
  def create
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_access_code
  def index
    if !@manager.survey
      redirect_to surveys_path
    else
      redirect_to gallerys_path
    end
    #@quarto = Hosting.first(:conditions => ['manager_id = ', @manager])
  end
  
  def print
    @manager.print = @manager.print + 1
    if @manager.save
      redirect_to @manager.tickets.first.passagem.url
    else
      flash[:msg] = "Ocorreu um erro na exibição de sua passagem,por favor, entre em contato com nosso suporte <a href='mailto:suporte@gestoresdeinformacao.com.br'>suporte@gestoresdeinformacao.com.br</a>"
      redirect_to access_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :simple_auth
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to managers_path, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to managers_path, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallerys_helper.rb
module GallerysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hostings_helper.rb
module HostingsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="BotBar"></div>
<div id="Footer"></div>
<div id="Sato7"><%=link_to(image_tag("sato7.png"), "http://www.sato7.com.br", :target => "_blank")%></div>

app/views/layouts/access.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>1º Encontro de Gestores da Informação</title>
  <%= stylesheet_link_tag "template" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "pngfix"%>
  <%= csrf_meta_tag %>
  
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-10816424-10']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<div id="TopBar"></div>
<div id="LogoAccess"><%=image_tag("logo_access.png")%></div>
<%= yield %>
<%=render :file => "layouts/_footer.html.erb"%>
</body>
</html>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "admin" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>

	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-10816424-10']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
  </head>
  <body>
	<div id="user_nav">
		<%= link_to "Home", root_path %>
		<% if current_user %>
			<span>&nbsp; Bem vindo <strong><%= current_user.username %> </strong>!</span>
			
			<%= link_to "Editar", edit_user_path(current_user) %>
			<%= link_to "Logout", logout_path %> 
			
		<% else %>
			<%= link_to "Registrar", new_admin_user_path %>
			<%= link_to "Login", login_path %>
		<% end %>
	</div>
	<div id="menu">
		<%=link_to "Gerenciar GIs", managers_path%> | 
		<%=link_to "Relatório de Acesso", reports_path%>
	</div>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>1º Encontro de Gestores da Informação</title>
  <%= stylesheet_link_tag "template" %>
  <%= javascript_include_tag "transparent" %>
  
  <%= csrf_meta_tag %>

	<%=yield :head%>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-10816424-10']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();	 
	  
	</script>
</head>
<body>
<div id="TopBar"></div>
<div id="General">
	<div id="Logo">
		Zaba
		<%=image_tag("logo_internas.png")%>
	</div>
	<!--<div id="Counter">
		
		<div id="DateTimer">
			<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="471" height="238" id="Counter" align="middle">
								<param name="allowScriptAccess" value="sameDomain" />
								<param name="allowFullScreen" value="false" />
								<param name="movie" value="/contador.swf" />
								<param name="quality" value="high" />
								<param name="wmode" value="transparent" />
								<embed wmode="transparent" src="contador.swf" quality="high"  width="471" height="238" name="Counter" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
							</object>
		
		</div>
	</div>-->
	
	<div class="clear">
		
	</div>
	<div id="Content">
		<%= yield %>
	</div>
</div>

<%=render :file => "layouts/_footer.html.erb"%>

</body>
</html>